version: '3'

services:
  api:
    build: .
    volumes:
      - ./:/home/node
    ports:
      - 3000:3000
  mongo:
    image: mongo:bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example